import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/utils/AuthProvide";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { dynamicNavLinksFunction } from "@/lib/utils";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BasketJoin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();
  const isAuth = await isAuthenticated();

  const { dynamicNavLinksArray, navLinksArray, success } =
    await dynamicNavLinksFunction();

  return (
    <AuthProvider>
      <html lang="en">
        <body
          // className={`${roboto.className} bg-gradient-to-t from-orange-200 via-orange-100 to-orange-100 flex flex-col min-h-screen max-w-[1100px] mx-auto`}
          className={`${roboto.className} mx-auto flex min-h-screen max-w-[1100px] flex-col bg-zinc-950 bg-gradient-to-t text-zinc-300`}
        >
          {/* <Suspense fallback={<div>Loading...</div>}> */}
          <Header
            isAuthenticated={isAuth}
                navLinksArray={success ? dynamicNavLinksArray : navLinksArray}
          />
          {/* </Suspense> */}
          <main className="sm:pb- grow px-4 pb-[calc(4rem+env(safe-area-inset-bottom))] pt-2">
            {children}
          </main>
          <Footer />
          <Toaster richColors />
        </body>
      </html>
    </AuthProvider>
  );
}
