import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/utils/AuthProvide";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { dynamicNavLinksFunction } from "@/lib/utils";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BasketJoin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, getPermissions } = getKindeServerSession();
  const isAuth = await isAuthenticated();
  const  permissions  = (await getPermissions())?.permissions;
  const { navLinks } = await dynamicNavLinksFunction(isAuth);

  

  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${roboto.className} mx-auto flex min-h-screen w-full max-w-[1100px] flex-col bg-zinc-950 text-zinc-300`}>
          <Header isAuthenticated={isAuth} navLinksArray={navLinks} permissions={permissions}/>
          {children}
          <Footer />
          <Toaster richColors />
        </body>
      </html>
    </AuthProvider>
  );
}
